<?php

namespace ContainerLe42o0U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthControllerService extends App_KernelProductionContainer
{
    /*
     * Gets the public 'App\Presentation\Web\Controller\HealthController' shared autowired service.
     *
     * @return \App\Presentation\Web\Controller\HealthController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Presentation\\Web\\Controller\\HealthController'] = new \App\Presentation\Web\Controller\HealthController();
    }
}
