<?php

namespace ContainerLe42o0U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeInfo_Resolver_ReflectionReturnService extends App_KernelProductionContainer
{
    /*
     * Gets the private 'type_info.resolver.reflection_return' shared service.
     *
     * @return \Symfony\Component\TypeInfo\TypeResolver\ReflectionReturnTypeResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['type_info.resolver.reflection_return'] = new \Symfony\Component\TypeInfo\TypeResolver\ReflectionReturnTypeResolver(($container->privates['type_info.resolver.reflection_type'] ?? $container->load('getTypeInfo_Resolver_ReflectionTypeService')), ($container->privates['type_info.type_context_factory'] ??= new \Symfony\Component\TypeInfo\TypeContext\TypeContextFactory(NULL, [])));
    }
}
