<?php

namespace ContainerLe42o0U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Loader_NativeFilesystemService extends App_KernelProductionContainer
{
    /*
     * Gets the private 'twig.loader.native_filesystem' shared service.
     *
     * @return \Twig\Loader\FilesystemLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['twig.loader.native_filesystem'] = $instance = new \Twig\Loader\FilesystemLoader([], \dirname(__DIR__, 4));

        $instance->addPath((\dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Resources/views'), 'Security');
        $instance->addPath((\dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Resources/views'), '!Security');
        $instance->addPath((\dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/templates'), 'TwigComponent');
        $instance->addPath((\dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/templates'), '!TwigComponent');
        $instance->addPath((\dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/templates'), 'LiveComponent');
        $instance->addPath((\dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/templates'), '!LiveComponent');
        $instance->addPath((\dirname(__DIR__, 4).'/vendor/symfony/ux-turbo/templates'), 'Turbo');
        $instance->addPath((\dirname(__DIR__, 4).'/vendor/symfony/ux-turbo/templates'), '!Turbo');
        $instance->addPath((\dirname(__DIR__, 4).'/templates'));
        $instance->addPath((\dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Resources/views/Form'));

        return $instance;
    }
}
