<?php

namespace ContainerLe42o0U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_ComponentHydratorService extends App_KernelProductionContainer
{
    /*
     * Gets the private 'ux.live_component.component_hydrator' shared service.
     *
     * @return \Symfony\UX\LiveComponent\LiveComponentHydrator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['ux.live_component.metadata_factory'] ?? $container->load('getUx_LiveComponent_MetadataFactoryService'));

        if (isset($container->privates['ux.live_component.component_hydrator'])) {
            return $container->privates['ux.live_component.component_hydrator'];
        }
        $b = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['ux.live_component.component_hydrator'])) {
            return $container->privates['ux.live_component.component_hydrator'];
        }

        $instance = new \Symfony\UX\LiveComponent\LiveComponentHydrator(new RewindableGenerator(fn () => new \EmptyIterator(), 0), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), $a, NULL, $container->getEnv('APP_SECRET'), $b);

        if (isset($container->privates['ux.live_component.component_hydrator'])) {
            return $container->privates['ux.live_component.component_hydrator'];
        }

        return $container->privates['ux.live_component.component_hydrator'] = $instance;
    }
}
