<?php

declare(strict_types=1);

namespace App\Domain\User\ValueObject;

use InvalidArgumentException;

/**
 * UserId Value Object
 * Represents the unique identifier for a user (Firebase UID)
 */
final readonly class UserId
{
    private function __construct(
        private string $value
    ) {
        if (empty($value) || strlen($value) > 128) {
            throw new InvalidArgumentException('Invalid user ID format');
        }
    }

    public static function fromString(string $value): self
    {
        return new self(trim($value));
    }

    public static function generate(): self
    {
        // For Firebase, the ID is generated by Firebase Auth
        // This is a placeholder for testing or migration scenarios
        return new self(uniqid('user_', true));
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function equals(UserId $other): bool
    {
        return $this->value === $other->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
