<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLe42o0U\App_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLe42o0U/App_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerLe42o0U.legacy');

    return;
}

if (!\class_exists(App_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerLe42o0U\App_KernelProductionContainer::class, App_KernelProductionContainer::class, false);
}

return new \ContainerLe42o0U\App_KernelProductionContainer([
    'container.build_hash' => 'Le42o0U',
    'container.build_id' => 'a8bfcd27',
    'container.build_time' => 1768367264,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLe42o0U');
